
steps:
  mtaBuild:
    platform: 'CF'
    
  cloudFoundryDeploy:
    cfOrg: "Camelot ITLab GmbH_Camelot ITLab GmbH CF"
    cfSpace: 'DEV'
    cfApiEndpoint: https://api.cf.eu10.hana.ondemand.com
    cfCredentialsId: 'CF_Credentials_Camelot'
